# Generated by Django 5.1.3 on 2024-11-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_student_details_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='department',
        ),
        migrations.DeleteModel(
            name='departments',
        ),
        migrations.DeleteModel(
            name='student_details',
        ),
    ]
